name: Pac-Man Terminal Game

on:
  workflow_dispatch:

jobs:
  run-pacman:
    runs-on: ubuntu-latest
    steps:
      - name: Run Pac-Man animation
        run: |
          echo "Starting Pac-Man..."
          echo -e "\033[1;33m"
          echo "Coooooool! Watch Pac-Man chase the ghost!"
          echo ""
          sleep 1
          for i in {1..20}; do
            echo -n "C"
            sleep 0.1
          done
          echo ""


          git add .
git commit -m "Add .github/workflows folder and example workflow"
git push origin main

